import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
global.wx={getStorageSync:()=>null,setStorageSync(){}};
const nav=require('../../miniprogram/packages/claim/shared/check-navigation.js');
const draft=require('../../miniprogram/shared/claim/draft.js');
const {groupIssues,groupAiIssues}=require('../../miniprogram/packages/claim/shared/review-groups.js');
const schema=require('../../miniprogram/shared/claim/schema.js');
function params(url){return Object.fromEntries(new URLSearchParams(url.split('?')[1]));}
test('numbering and navigation follow every check across groups, including checks in the same column',()=>{
  const groups=groupIssues([{step:3,field:'evidence',title:'证据一'},{step:0,field:'totalAmount',title:'金额'},{step:3,field:'evidence',title:'证据二',targetRowId:'row-two'}],schema.steps);
  const items=groups.flatMap(group=>group.items);
  assert.deepEqual(items.map(item=>item.displayNumber),[1,2,3]);
  const first=params(nav.start(items,0));
  assert.equal(nav.move(first.checks,0,-1).message,'已经是第一项');
  const second=nav.move(first.checks,0,1).url;
  assert.ok(second.startsWith(draft.pagePath(3)));
  const third=nav.move(first.checks,1,1).url;
  assert.ok(third.startsWith(draft.pagePath(3)));
  assert.equal(params(third).row,'row-two');
  assert.equal(nav.info(first.checks,2).total,3);
  assert.equal(nav.move(first.checks,2,1).message,'已经是最后一项');
  assert.equal(params(nav.move(first.checks,2,-1).url).checkIndex,'1');
  const previousCase=draft.get().caseId;draft.get().caseId='new-case';
  assert.ok(nav.move(first.checks,1,1).message.includes('重新选择'));
  draft.get().caseId=previousCase;
});
test('end buttons show a dialog rather than navigating or being disabled',()=>{
  let definition,modal,redirect;
  global.Component=value=>{definition=value;};
  global.wx.showModal=value=>{modal=value;};global.wx.redirectTo=value=>{redirect=value;};
  require('../../miniprogram/packages/claim/components/claim-form/index.js');
  const query=params(nav.start([{step:1,field:'plaintiffName',title:'姓名'}],0));
  const context={properties:{checks:query.checks,checkIndex:0}};
  definition.methods.moveCheck.call(context,-1);
  assert.equal(modal.content,'已经是第一项');assert.equal(modal.showCancel,false);assert.equal(redirect,undefined);
  definition.methods.moveCheck.call(context,1);assert.equal(modal.content,'已经是最后一项');
});
test('AI and system checks have independent numbering, lists and highlight labels',()=>{
  const system=params(nav.start([{step:1,title:'系统一'},{step:3,title:'系统二'}],0));
  assert.equal(nav.info(system.checks,0).label,'系统检查');
  const ai=params(nav.start([{step:0,title:'AI一',displayNumber:1},{step:4,title:'AI二',displayNumber:2}],0,'ai'));
  assert.equal(nav.info(ai.checks,0).label,'AI检查');
  assert.equal(nav.info(ai.checks,0).item.displayNumber,1);
  assert.equal(nav.info(ai.checks,0).total,2);
  assert.equal(nav.move(ai.checks,1,1).message,'已经是最后一项');
  let definition,opened;
  global.Component=value=>{definition=value;};
  const path=require.resolve('../../miniprogram/packages/claim/components/claim-form/index.js');delete require.cache[path];require(path);
  global.wx.navigateTo=value=>{opened=params(value.url);};
  const context={data:{issueGroups:[{items:[{step:1,sourceIndex:3,title:'系统一'},{step:3,sourceIndex:0,title:'系统二'}]}],ai:{issues:[{step:0,title:'AI一'},{step:4,title:'AI二'}]}}};
  definition.methods.openCheck.call(context,'ai',0);
  assert.equal(nav.info(opened.checks,0).label,'AI检查');assert.equal(nav.info(opened.checks,0).total,2);
  definition.methods.openCheck.call(context,'local',0);
  assert.equal(opened.checkIndex,'1');assert.equal(nav.info(opened.checks,1).label,'系统检查');assert.equal(nav.info(opened.checks,1).total,2);
});
test('AI group collapse and navigation use the grouped display order, not original model order',()=>{
  let definition,opened;
  global.Component=value=>{definition=value;};
  const path=require.resolve('../../miniprogram/packages/claim/components/claim-form/index.js');delete require.cache[path];require(path);
  global.wx.navigateTo=value=>{opened=params(value.url);};
  const issues=[{step:3,field:'evidence',title:'送货凭证'},{step:0,field:'totalAmount',title:'金额'}];
  const context={data:{ai:{issues},aiGroups:groupAiIssues(issues).map(group=>({...group,expanded:true}))},setData(value){this.lastChange=value;}};
  definition.methods.openCheck.call(context,'ai',0);
  assert.equal(opened.checkIndex,'1');assert.equal(nav.info(opened.checks,1).item.title,'送货凭证');assert.equal(nav.info(opened.checks,1).item.displayNumber,2);
  assert.equal(params(nav.move(opened.checks,1,-1).url).field,'totalAmount');
  definition.methods.toggleAiGroup.call(context,{currentTarget:{dataset:{key:'facts'}}});
  assert.equal(context.collapsedAiGroups.facts,true);assert.equal(context.lastChange['aiGroups[1].expanded'],false);
});
