import { readFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import { load } from 'cheerio';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const source = await readFile(resolve(root, 'claim-backend/engine/app.js'), 'utf8');
const contractSource = await readFile(resolve(root, 'claim-backend/engine/contracts/jiujiang.js'), 'utf8');
let generatedId=0;
const randomUUID=()=>`00000000-0000-4000-8000-${String(++generatedId).padStart(12,'0')}`;
const context = vm.createContext({ window: {}, crypto: { randomUUID }, structuredClone });
vm.runInContext(contractSource, context);
vm.runInContext(source.slice(0, source.indexOf('\nlet state = loadState();')), context);
const defaults = vm.runInContext('structuredClone(defaultState)', context);
vm.runInContext('let state; let uploads; function hydrateForm(){} function refresh(){} function toast(){}', context);
vm.runInContext(source.slice(source.indexOf('function fillSample()'), source.indexOf('function resetAll()')) + ';fillSample();', context);
const sample = vm.runInContext('state', context);
const contract = context.window.JIUJIANG_CONTRACT;
const $ = load(await readFile(resolve(root, 'claim-backend/engine/index.html'), 'utf8'));
const steps = [];
$('.form-step').each((index, panel) => {
  const fields = [];
  $(panel).find('[data-field]').each((_i, element) => {
    const el = $(element), label = el.closest('label'), key = el.attr('data-field');
    if (fields.some(x => x.key === key)) return;
    const labelText = label.find('span').first().clone(); labelText.find('i,em,small').remove();
    const item = { key, label: labelText.text().trim() || key, required: label.find('i').length > 0, placeholder: el.attr('placeholder') || '', kind: element.tagName === 'textarea' ? 'textarea' : el.attr('type') === 'checkbox' ? 'switch' : element.tagName === 'select' ? 'select' : el.attr('type') === 'date' ? 'date' : 'input', inputType: el.attr('type') === 'number' ? 'digit' : el.attr('inputmode') === 'tel' ? 'number' : 'text' };
    if (item.kind === 'switch') item.label = label.find('b').first().text() || label.find('span').text();
    if (item.kind === 'select') item.options = el.find('option').map((_j, option) => ({ value: $(option).attr('value') === undefined ? $(option).text() : $(option).attr('value'), label: $(option).text() })).get();
    if (key === 'court') item.options = [{ value: '', label: '请选择' }, ...contract.courts.map(value => ({ value, label: value }))];
    const classes = (label.attr('class') || '') + ' ' + el.parents().map((_j,p) => $(p).attr('class') || '').get().join(' ');
    if (classes.includes('plaintiff-natural')) item.condition = 'plaintiff-natural';
    if (classes.includes('plaintiff-company')) item.condition = 'plaintiff-company';
    if (classes.includes('defendant-natural')) item.condition = 'defendant-natural';
    if (classes.includes('defendant-company')) item.condition = 'defendant-company';
    if (classes.includes('written-contract-only')) item.condition = 'written';
    if (['dealFormation','deliveryReceipt','priceBasis','debtAcknowledgement'].includes(key)) item.condition = 'unwritten';
    if (key.startsWith('agent')) item.condition = 'agent';
    if (key.startsWith('refund')) item.condition = 'refund';
    fields.push(item);
  });
  const titles = ['起诉状','当事人身份证明','被告线索（辅助）','证据目录','送达确认和收款账户','检查下载'];
  steps.push({ index, title: titles[index], fields });
});
const data = { defaults, sample, steps, courts: contract.courts, grounds: contract.jurisdictionGrounds.map(x => ({ value: x.value, label: x.short, writtenOnly: !!x.writtenContractOnly })) };
const files = { 'miniprogram/shared/claim/schema.js': '/* 从已验收的网页字段生成，运行 npm run generate-client 更新。 */\nmodule.exports = ' + JSON.stringify(data, null, 2) + ';\n', 'miniprogram/shared/claim/contract.js': 'const window = {};\n' + contractSource + '\nmodule.exports = window.JIUJIANG_CONTRACT;\n' };
let patch = '*** Begin Patch\n';
for (const [file, content] of Object.entries(files)) patch += '*** Add File: ' + resolve(root, file) + '\n' + content.split('\n').map(line => '+' + line).join('\n') + '\n';
patch += '*** End Patch';
process.stdout.write(patch);
